"""Batch 2 — 11 User-Curated Problems."""
from typing import List, Dict, Any

BATCH2_PROBLEMS: List[Dict[str, Any]] = [
    {
        "slug": "coupon_code_frequency",
        "title": "Coupon Code Frequency",
        "topic": "Arrays & Hashing",
        "difficulty": "Easy",
        "tags": ["hashing", "frequency-map"],
        "domains": ["ecommerce", "backend"],
        "statement": "An online store records the numeric code printed on every coupon used during a campaign. The marketing team wants to know whether any coupon code was used at least k times. Determine the largest usage count among all distinct coupon codes.",
        "inputFormat": "Line 1 contains n and k. Line 2 contains n integer coupon codes.",
        "outputFormat": "Print the largest number of times any single coupon code appears.",
        "constraints": "1 <= n <= 200000. 1 <= k <= n. Each coupon code is an integer from -10^9 to 10^9.",
        "sampleTestCases": [
            {"input": "8 2\n4 9 4 2 9 9 7 4\n", "output": "3", "explanation": "Codes 4 and 9 each occur three times, which is the largest frequency."},
            {"input": "5 4\n1 2 3 4 5\n", "output": "1", "explanation": "Every code appears exactly once, so the maximum frequency is 1."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Use a frequency map to count each coupon code and track the largest count.",
        "referenceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=a[2:2+n];d={};ans=0\nfor v in x:\n d[v]=d.get(v,0)+1\n ans=max(ans,d[v])\nprint(ans)",
        "bruteForceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=a[2:2+n];print(max(x.count(v) for v in set(x)))",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,30));k=n if m=='edge' else r.randint(1,n);x=[r.randint(-8,8) for _ in range(n)];print(n,k);print(*x)",
        "inputValidator": "import sys\ntry:\n a=list(map(int,sys.stdin.buffer.read().split()));n,k=a[:2];assert 1<=n<=200000 and 1<=k<=n and len(a)==n+2;assert all(-10**9<=x<=10**9 for x in a[2:])\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1 1\n0\n","5 5\n7 7 7 7 7\n","5 1\n1 2 3 4 5\n","6 3\n2 2 2 9 9 1\n","7 2\n-3 -3 -2 -2 -1 0 1\n","4 4\n1000000000 1000000000 1000000000 1000000000\n"],
        "wrongSolutions": [
            {"name": "distinct_count", "description": "Outputs the number of distinct codes instead of the largest frequency.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];print(len(set(a[2:2+n])))"},
            {"name": "first_frequency", "description": "Reports only the frequency of the first coupon code.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=a[2:2+n];print(x.count(x[0]))"},
            {"name": "too_slow_but_correct", "description": "Counts every distinct code by scanning the entire array, producing quadratic behavior.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=a[2:2+n];print(max(x.count(v) for v in set(x)))"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "delivery_pair_totals",
        "title": "Delivery Pair Totals",
        "topic": "Arrays & Hashing",
        "difficulty": "Medium",
        "tags": ["hashing", "prefix-sum", "pair-counting"],
        "domains": ["logistics", "data"],
        "statement": "A delivery platform records the number of packages handled by each courier during a shift. Management wants to know how many pairs of couriers handled exactly target packages together. Each unordered pair of different couriers counts once.",
        "inputFormat": "Line 1 contains n and target T. Line 2 contains n integer package counts.",
        "outputFormat": "Print the number of unordered pairs whose two package counts add up to T.",
        "constraints": "2 <= n <= 200000. -10^9 <= T <= 10^9. Each package count is an integer from -10^9 to 10^9.",
        "sampleTestCases": [
            {"input": "6 10\n3 7 4 6 5 5\n", "output": "3", "explanation": "The valid pairs are 3+7, 4+6, and 5+5."},
            {"input": "5 0\n-2 2 -2 4 -4\n", "output": "3", "explanation": "The pairs are -2+2 twice and 4+(-4) once."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Scan left to right and count how many previously seen values equal target minus the current value.",
        "referenceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=a[2:2+n];d={};ans=0\nfor v in x:\n ans+=d.get(T-v,0)\n d[v]=d.get(v,0)+1\nprint(ans)",
        "bruteForceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=a[2:2+n];ans=0\nfor i in range(n):\n for j in range(i):\n  if x[i]+x[j]==T:ans+=1\nprint(ans)",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (2 if m=='edge' else r.randint(2,28));T=r.randint(-20,20);x=[r.randint(-20,20) for _ in range(n)];print(n,T);print(*x)",
        "inputValidator": "import sys\ntry:\n a=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];assert 2<=n<=200000 and -10**9<=T<=10**9 and len(a)==n+2;assert all(-10**9<=x<=10**9 for x in a[2:])\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["2 0\n0 0\n","2 0\n-1000000000 1000000000\n","5 10\n5 5 5 5 5\n","5 100\n1 2 3 4 5\n","6 0\n-2 2 -2 2 0 0\n","4 -5\n-2 -3 7 8\n"],
        "wrongSolutions": [
            {"name": "set_pairs", "description": "Counts distinct value pairs instead of courier position pairs, losing multiplicities.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=set(a[2:2+n]);print(sum(1 for v in x if T-v in x and v<=T-v))"},
            {"name": "includes_self", "description": "Counts a value against itself even when only one occurrence exists.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];d={};ans=0\nfor v in a[2:2+n]:d[v]=d.get(v,0)+1\nfor v,c in d.items():ans+=c*d.get(T-v,0)\nprint(ans//2)"},
            {"name": "too_slow_but_correct", "description": "Checks all unordered pairs and is quadratic.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=a[2:2+n];ans=0\nfor i in range(n):\n for j in range(i):\n  ans+=x[i]+x[j]==T\nprint(ans)"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "invoice_digit_cleanup",
        "title": "Invoice Digit Cleanup",
        "topic": "Strings",
        "difficulty": "Easy",
        "tags": ["strings", "parsing"],
        "domains": ["fintech", "backend"],
        "statement": "A billing system receives an invoice reference containing digits and separator characters such as hyphens and spaces. Before indexing, it removes every non-digit character while preserving the original order of the digits. Print the cleaned reference.",
        "inputFormat": "Line 1 contains an integer n. Line 2 contains a string of exactly n characters. Each character is a digit, lowercase letter, uppercase letter, hyphen, underscore, or space.",
        "outputFormat": "Print the string formed by keeping only the digits from the input reference. If there are no digits, print an empty line.",
        "constraints": "1 <= n <= 200000. The input string contains only ASCII letters, digits, hyphen, underscore, and space.",
        "sampleTestCases": [
            {"input": "14\nINV-20 A7_501\n", "output": "207501", "explanation": "Only 2, 0, 7, 5, 0, and 1 are retained."},
            {"input": "9\nabc-_ XYZ\n", "output": "", "explanation": "The reference contains no digits, so the cleaned result is empty."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Scan the reference once and append only characters in the digit range.",
        "referenceSolution": "import sys\na=sys.stdin.buffer.read().splitlines();s=a[1].decode();print(''.join(c for c in s if '0'<=c<='9'))",
        "bruteForceSolution": "import sys\na=sys.stdin.buffer.read().splitlines();s=a[1].decode();out=''\nfor c in s:\n if c.isdigit():out+=c\nprint(out)",
        "inputGenerator": "import sys,random,string\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,40));chars=string.ascii_letters+string.digits+'-_ ';s=''.join(r.choice(chars) for _ in range(n));print(n);print(s)",
        "inputValidator": "import sys\ntry:\n lines=sys.stdin.read().splitlines();assert len(lines)==2;n=int(lines[0]);s=lines[1];allowed=set('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_ ');assert 1<=n<=200000 and len(s)==n and all(c in allowed for c in s)\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1\n0\n","5\n12345\n","6\nabcdef\n","9\n1-2_3 4\n","7\n9999999\n","4\n- - \n"],
        "wrongSolutions": [
            {"name": "remove_digits", "description": "Keeps separators instead of digits.", "code": "import sys\ns=sys.stdin.read().splitlines()[1];print(''.join(c for c in s if not c.isdigit()))"},
            {"name": "sort_digits", "description": "Keeps the correct characters but destroys their original order.", "code": "import sys\ns=sys.stdin.read().splitlines()[1];print(''.join(sorted(c for c in s if c.isdigit())))"},
            {"name": "too_slow_but_correct", "description": "Repeatedly rebuilds the output string, causing quadratic copying.", "code": "import sys\ns=sys.stdin.read().splitlines()[1];out=''\nfor c in s:\n if c.isdigit():out=out+c\nprint(out)"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "chat_keyword_run",
        "title": "Longest Quiet Streak",
        "topic": "Strings",
        "difficulty": "Medium",
        "tags": ["strings", "run-length", "scanning"],
        "domains": ["general", "data"],
        "statement": "A support chat marks every message with either Q for a quiet message or A for an active message. A quiet streak is a consecutive run of Q characters. Find the length of the longest quiet streak in the transcript.",
        "inputFormat": "Line 1 contains n. Line 2 contains a string of exactly n characters, each either Q or A.",
        "outputFormat": "Print the length of the longest consecutive run of Q characters.",
        "constraints": "1 <= n <= 200000. The transcript contains only Q and A.",
        "sampleTestCases": [
            {"input": "10\nAQQAQAAAQQ\n", "output": "2", "explanation": "The longest runs of Q are positions 2-3 and 9-10, both of length 2."},
            {"input": "7\nQQQQQQQ\n", "output": "7", "explanation": "Every message is quiet, forming one streak of length 7."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Maintain the current consecutive Q count and reset it whenever an A is encountered.",
        "referenceSolution": "import sys\na=sys.stdin.read().split();s=a[1];cur=ans=0\nfor c in s:\n if c=='Q':cur+=1;ans=max(ans,cur)\n else:cur=0\nprint(ans)",
        "bruteForceSolution": "import sys\na=sys.stdin.read().split();s=a[1];best=0\nfor i in range(len(s)):\n for j in range(i,len(s)):\n  if all(c=='Q' for c in s[i:j+1]):best=max(best,j-i+1)\nprint(best)",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,35));s=''.join(r.choice('QA') for _ in range(n));print(n);print(s)",
        "inputValidator": "import sys\ntry:\n a=sys.stdin.read().split();assert len(a)==2;n=int(a[0]);s=a[1];assert 1<=n<=200000 and len(s)==n and all(c in 'QA' for c in s)\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1\nQ\n","1\nA\n","7\nQQQQQQQ\n","7\nAAAAAAA\n","9\nQAQQAQQQQ\n","8\nAQQQQAAA\n"],
        "wrongSolutions": [
            {"name": "total_q", "description": "Counts all Q messages instead of the longest consecutive run.", "code": "import sys\na=sys.stdin.read().split();print(a[1].count('Q'))"},
            {"name": "starts_only", "description": "Measures only a Q run beginning at the first character.", "code": "import sys\na=sys.stdin.read().split();s=a[1];i=0\nwhile i<len(s) and s[i]=='Q':i+=1\nprint(i)"},
            {"name": "too_slow_but_correct", "description": "Tests every substring and can take cubic time.", "code": "import sys\na=sys.stdin.read().split();s=a[1];best=0\nfor i in range(len(s)):\n for j in range(i,len(s)):\n  if all(c=='Q' for c in s[i:j+1]):best=max(best,j-i+1)\nprint(best)"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "package_pairing_threshold",
        "title": "Package Pairing Threshold",
        "topic": "Two Pointers",
        "difficulty": "Medium",
        "tags": ["two-pointers", "sorting", "greedy"],
        "domains": ["logistics", "ecommerce"],
        "statement": "A packing line has package weights and a preferred combined-weight threshold. A pair is acceptable when the two package weights add to at least the threshold. Each package may be used in at most one pair. Find the maximum number of disjoint acceptable pairs.",
        "inputFormat": "Line 1 contains n and threshold T. Line 2 contains n integer package weights.",
        "outputFormat": "Print the maximum number of disjoint pairs whose combined weight is at least T.",
        "constraints": "2 <= n <= 200000. 1 <= T <= 10^9. Each package weight is an integer from 1 to 10^9.",
        "sampleTestCases": [
            {"input": "6 10\n2 8 3 7 4 6\n", "output": "3", "explanation": "The pairs 2+8, 3+7, and 4+6 all meet the threshold."},
            {"input": "5 12\n2 3 9 10 11\n", "output": "2", "explanation": "The best choices are 2+11 and 3+10; the remaining 9 cannot form another pair."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Sort the weights and pair the lightest with the heaviest; if they reach the threshold, keep the pair, otherwise the lightest cannot pair with anyone.",
        "referenceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=sorted(a[2:2+n]);i,j=0,n-1;ans=0\nwhile i<j:\n if x[i]+x[j]>=T:ans+=1;i+=1;j-=1\n else:i+=1\nprint(ans)",
        "bruteForceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=a[2:2+n];dp=[0]*(1<<n)\nfor m in range(1<<n):\n i=next((i for i in range(n) if not(m>>i&1)),None)\n if i is None:continue\n dp[m|1<<i]=max(dp[m|1<<i],dp[m])\n for j in range(i+1,n):\n  if not(m>>j&1) and x[i]+x[j]>=T:dp[m|1<<i|1<<j]=max(dp[m|1<<i|1<<j],dp[m]+1)\nprint(dp[-1])",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (2 if m=='edge' else r.randint(2,16));T=r.randint(2,100) if m!='large' else 10**9;x=[r.randint(1,T) for _ in range(n)];print(n,T);print(*x)",
        "inputValidator": "import sys\ntry:\n a=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];assert 2<=n<=200000 and 1<=T<=10**9 and len(a)==n+2;assert all(1<=x<=10**9 for x in a[2:])\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["2 10\n5 5\n","2 10\n4 5\n","5 10\n5 5 5 5 5\n","6 10\n1 2 3 8 9 10\n","5 100\n1 2 3 4 5\n","6 7\n1 1 6 6 6 6\n"],
        "wrongSolutions": [
            {"name": "heaviest_first", "description": "Pairs the heaviest remaining packages together without checking whether this maximizes the pair count.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=sorted(a[2:2+n]);ans=0\nwhile len(x)>1:\n if x[-1]+x[-2]>=T:ans+=1;x.pop();x.pop()\n else:x.pop()\nprint(ans)"},
            {"name": "count_overlapping", "description": "Counts qualifying adjacent pairs after sorting without consuming both packages.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=sorted(a[2:2+n]);print(sum(x[i]+x[i+1]>=T for i in range(n-1)))"},
            {"name": "too_slow_but_correct", "description": "Uses exponential subset dynamic programming.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,T=a[:2];x=a[2:2+n];dp=[0]*(1<<n)\nfor m in range(1<<n):\n i=next((i for i in range(n) if not(m>>i&1)),None)\n if i is None:continue\n dp[m|1<<i]=max(dp[m|1<<i],dp[m])\n for j in range(i+1,n):\n  if not(m>>j&1) and x[i]+x[j]>=T:dp[m|1<<i|1<<j]=max(dp[m|1<<i|1<<j],dp[m]+1)\nprint(dp[-1])"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "network_error_window",
        "title": "Network Error Window",
        "topic": "Sliding Window",
        "difficulty": "Easy",
        "tags": ["sliding-window", "frequency-map"],
        "domains": ["devops", "backend"],
        "statement": "A monitoring stream contains one integer error code per request. For a fixed window of k consecutive requests, an incident is considered diverse when it contains at least d distinct error codes. Count how many windows are diverse.",
        "inputFormat": "Line 1 contains n, k, and d. Line 2 contains n integer error codes.",
        "outputFormat": "Print the number of length-k windows containing at least d distinct error codes.",
        "constraints": "1 <= d <= k <= n <= 200000. Each error code is an integer from -10^9 to 10^9.",
        "sampleTestCases": [
            {"input": "7 3 2\n1 1 2 3 3 4 4\n", "output": "4", "explanation": "The first, second, third, and fifth windows contain at least two distinct codes."},
            {"input": "5 2 2\n7 7 7 8 8\n", "output": "1", "explanation": "Only the window [7,8] contains two distinct error codes."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Maintain a frequency map for the current window so its distinct-code count changes in constant expected time as endpoints move.",
        "referenceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k,d=a[:3];x=a[3:3+n];f={};distinct=0\nfor v in x[:k]:\n if f.get(v,0)==0:distinct+=1\n f[v]=f.get(v,0)+1\nans=distinct>=d\nfor i in range(k,n):\n v=x[i];f[v]=f.get(v,0)+1\n if f[x[i-k]]==1:del f[x[i-k]];distinct-=1\n else:f[x[i-k]]-=1\n ans+=distinct>=d\nprint(ans)",
        "bruteForceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k,d=a[:3];x=a[3:3+n];print(sum(len(set(x[i:i+k]))>=d for i in range(n-k+1)))",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,35));k=n if m=='edge' else r.randint(1,n);d=r.randint(1,k);x=[r.randint(-8,8) for _ in range(n)];print(n,k,d);print(*x)",
        "inputValidator": "import sys\ntry:\n a=list(map(int,sys.stdin.buffer.read().split()));n,k,d=a[:3];assert 1<=d<=k<=n<=200000 and len(a)==n+3;assert all(-10**9<=x<=10**9 for x in a[3:])\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1 1 1\n5\n","5 5 1\n2 2 2 2 2\n","5 5 2\n2 2 2 2 2\n","6 1 1\n1 2 3 4 5 6\n","7 3 3\n1 2 3 3 3 4 5\n","6 2 2\n1 1 2 2 3 3\n"],
        "wrongSolutions": [
            {"name": "global_distinct", "description": "Uses the number of distinct codes in the entire stream for every window.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k,d=a[:3];x=a[3:3+n];print((n-k+1) if len(set(x))>=d else 0)"},
            {"name": "strict_greater", "description": "Uses > d instead of >= d.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k,d=a[:3];x=a[3:3+n];print(sum(len(set(x[i:i+k]))>d for i in range(n-k+1)))"},
            {"name": "too_slow_but_correct", "description": "Builds a fresh set for every window, taking quadratic time in the worst case.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k,d=a[:3];x=a[3:3+n];print(sum(len(set(x[i:i+k]))>=d for i in range(n-k+1)))"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "traffic_load_window",
        "title": "Traffic Load Window",
        "topic": "Sliding Window",
        "difficulty": "Medium",
        "tags": ["sliding-window", "prefix-sum", "optimization"],
        "domains": ["devops", "backend"],
        "statement": "A web gateway records the number of requests arriving each minute. Engineers want to inspect a continuous period of exactly k minutes with the greatest total traffic. Find that maximum total.",
        "inputFormat": "Line 1 contains n and k. Line 2 contains n non-negative integer request counts.",
        "outputFormat": "Print the largest sum among all consecutive blocks of exactly k request counts.",
        "constraints": "1 <= k <= n <= 200000. 0 <= each request count <= 10^9.",
        "sampleTestCases": [
            {"input": "7 3\n4 2 7 1 5 3 6\n", "output": "14", "explanation": "The final block 5+3+6 totals 14, the largest three-minute traffic load."},
            {"input": "5 2\n10 1 2 9 3\n", "output": "11", "explanation": "The first block totals 11 and the middle block 2+9 also totals 11."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Compute the first window sum and update it by subtracting the outgoing value and adding the incoming value.",
        "referenceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k=a[:2];x=a[2:2+n];cur=sum(x[:k]);ans=cur\nfor i in range(k,n):cur+=x[i]-x[i-k];ans=max(ans,cur)\nprint(ans)",
        "bruteForceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k=a[:2];x=a[2:2+n];print(max(sum(x[i:i+k]) for i in range(n-k+1)))",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,35));k=n if m=='edge' else r.randint(1,n);x=[r.randint(0,100) for _ in range(n)];print(n,k);print(*x)",
        "inputValidator": "import sys\ntry:\n a=list(map(int,sys.stdin.buffer.read().split()));n,k=a[:2];assert 1<=k<=n<=200000 and len(a)==n+2;assert all(0<=x<=10**9 for x in a[2:])\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1 1\n0\n","1 1\n1000000000\n","5 5\n4 4 4 4 4\n","6 1\n3 8 1 9 2 7\n","7 3\n9 1 1 9 1 1 9\n","5 2\n0 0 0 0 0\n"],
        "wrongSolutions": [
            {"name": "minimum_window", "description": "Returns the smallest window sum instead of the largest.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k=a[:2];x=a[2:2+n];print(min(sum(x[i:i+k]) for i in range(n-k+1)))"},
            {"name": "wrong_window_size", "description": "Uses windows of k+1 elements.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k=a[:2];x=a[2:2+n];print(max(sum(x[i:i+k+1]) for i in range(n-k)))"},
            {"name": "too_slow_but_correct", "description": "Recomputes each window sum from scratch.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n,k=a[:2];x=a[2:2+n];print(max(sum(x[i:i+k]) for i in range(n-k+1)))"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "printer_job_queue",
        "title": "Printer Job Queue",
        "topic": "Stack & Queue",
        "difficulty": "Easy",
        "tags": ["queue", "simulation"],
        "domains": ["backend", "general"],
        "statement": "A shared printer processes jobs in first-in-first-out order. Each job has a positive number of pages, and the printer handles one page per second. Given the jobs in arrival order, determine which job finishes last and how many seconds have elapsed when it finishes.",
        "inputFormat": "Line 1 contains n. Line 2 contains n positive integers, where the i-th value is the number of pages in job i.",
        "outputFormat": "Print two integers: the 1-based index of the last finishing job and the total finishing time.",
        "constraints": "1 <= n <= 200000. 1 <= each page count <= 10^9.",
        "sampleTestCases": [
            {"input": "4\n5 2 7 3\n", "output": "4 17", "explanation": "The fourth job finishes after all 17 pages have been printed."},
            {"input": "3\n9 1 4\n", "output": "3 14", "explanation": "FIFO processing makes job 3 finish after 9+1+4 = 14 seconds."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "FIFO order means the last arriving job is necessarily the last to finish, and its finish time is the total page count.",
        "referenceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=a[1:1+n];print(n,sum(x))",
        "bruteForceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=a[1:1+n];time=0\nfinish=[]\nfor i,v in enumerate(x,1):time+=v;finish.append((time,i))\nfinish.sort();print(finish[-1][1],finish[-1][0])",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,30));x=[r.randint(1,1000) for _ in range(n)];print(n);print(*x)",
        "inputValidator": "import sys\ntry:\n a=list(map(int,sys.stdin.buffer.read().split()));n=a[0];assert 1<=n<=200000 and len(a)==n+1;assert all(1<=x<=10**9 for x in a[1:])\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1\n1\n","1\n1000000000\n","5\n7 7 7 7 7\n","5\n1 2 3 4 5\n","6\n5 1 5 1 5 1\n","3\n1000000000 1000000000 1000000000\n"],
        "wrongSolutions": [
            {"name": "largest_job", "description": "Returns the job with the most pages rather than the final FIFO job.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=a[1:1+n];i=max(range(n),key=x.__getitem__);print(i+1,x[i])"},
            {"name": "finish_time_only", "description": "Prints only the total time and omits the required job index.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));print(sum(a[1:]))"},
            {"name": "too_slow_but_correct", "description": "Simulates individual seconds rather than accumulating page counts.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=a[1:1+n];q=list(range(n));time=0\nwhile q:\n i=q.pop(0);time+=x[i]\nprint(n,time)"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "browser_back_steps",
        "title": "Browser Back Steps",
        "topic": "Stack & Queue",
        "difficulty": "Medium",
        "tags": ["stack", "simulation"],
        "domains": ["frontend", "general"],
        "statement": "A browser records page visits. A BACK command moves to the previously visited page, while a VISIT command opens a new page and clears the forward history. After processing all commands, report the current page. The browser starts at page HOME.",
        "inputFormat": "Line 1 contains n. Each of the next n lines contains either \"VISIT page\" or \"BACK\". A page is a lowercase string of 1 to 20 letters. BACK is guaranteed never to be issued when there is no previous page.",
        "outputFormat": "Print the name of the current page after all commands.",
        "constraints": "1 <= n <= 200000. Each command is either BACK or VISIT followed by a lowercase page name of length 1 to 20. The initial page is HOME.",
        "sampleTestCases": [
            {"input": "5\nVISIT alpha\nVISIT beta\nBACK\nVISIT gamma\nBACK\n", "output": "alpha", "explanation": "The browser goes HOME -> alpha -> beta -> alpha -> gamma -> alpha."},
            {"input": "4\nVISIT shop\nVISIT cart\nBACK\nBACK\n", "output": "HOME", "explanation": "The two BACK commands return from cart to shop and then from shop to HOME."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Keep a stack of visited pages; VISIT pushes a page and BACK removes the current page.",
        "referenceSolution": "import sys\na=sys.stdin.read().splitlines();n=int(a[0]);st=['HOME']\nfor line in a[1:n+1]:\n p=line.split()\n if p[0]=='VISIT':st.append(p[1])\n else:st.pop()\nprint(st[-1])",
        "bruteForceSolution": "import sys\na=sys.stdin.read().splitlines();n=int(a[0]);history=['HOME'];cur=0\nfor line in a[1:n+1]:\n p=line.split()\n if p[0]=='VISIT':\n  history=history[:cur+1]+[p[1]];cur+=1\n else:cur-=1\nprint(history[cur])",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,30));lines=[];depth=0\nfor i in range(n):\n if depth>0 and r.random()<.35:lines.append('BACK');depth-=1\n else:lines.append('VISIT p'+str(i));depth+=1\nprint(n);print('\\n'.join(lines))",
        "inputValidator": "import sys\ntry:\n a=sys.stdin.read().splitlines();n=int(a[0]);assert 1<=n<=200000 and len(a)==n+1;depth=0\n for line in a[1:]:\n  p=line.split();assert p[0] in ('BACK','VISIT')\n  if p[0]=='BACK':assert len(p)==1 and depth>0;depth-=1\n  else:assert len(p)==2 and 1<=len(p[1])<=20 and p[1].islower() and p[1].isalpha();depth+=1\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1\nVISIT a\n","2\nVISIT a\nBACK\n","5\nVISIT a\nVISIT b\nBACK\nBACK\nVISIT c\n","4\nVISIT a\nVISIT b\nBACK\nVISIT c\n","6\nVISIT home\nVISIT x\nBACK\nVISIT y\nBACK\nBACK\n","3\nVISIT z\nBACK\nVISIT q\n"],
        "wrongSolutions": [
            {"name": "back_without_pop", "description": "Moves backward by indexing history but leaves the current page in the stack.", "code": "import sys\na=sys.stdin.read().splitlines();n=int(a[0]);st=['HOME'];cur=0\nfor line in a[1:]:\n p=line.split()\n if p[0]=='VISIT':st.append(p[1]);cur+=1\n else:cur-=1\nprint(st[cur])"},
            {"name": "visit_keeps_forward", "description": "Fails to discard the old forward path when a new page is visited.", "code": "import sys\na=sys.stdin.read().splitlines();n=int(a[0]);hist=['HOME'];cur=0\nfor line in a[1:]:\n p=line.split()\n if p[0]=='VISIT':hist.append(p[1]);cur+=1\n else:cur-=1\nprint(hist[cur])"},
            {"name": "too_slow_but_correct", "description": "Copies the entire history list on every VISIT.", "code": "import sys\na=sys.stdin.read().splitlines();n=int(a[0]);hist=['HOME'];cur=0\nfor line in a[1:]:\n p=line.split()\n if p[0]=='VISIT':hist=hist[:cur+1]+[p[1]];cur+=1\n else:cur-=1\nprint(hist[cur])"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "meeting_overlap_peak",
        "title": "Meeting Room Peak",
        "topic": "Sorting & Intervals",
        "difficulty": "Medium",
        "tags": ["sorting", "intervals", "sweep-line"],
        "domains": ["general", "backend"],
        "statement": "A company records meetings by their start and end times. A meeting occupies a room from its start time up to, but not including, its end time. Determine the largest number of meetings happening simultaneously.",
        "inputFormat": "Line 1 contains n. Each of the next n lines contains two integers start and end, with start < end.",
        "outputFormat": "Print the maximum number of meetings that overlap at any instant.",
        "constraints": "1 <= n <= 200000. 0 <= start < end <= 10^9.",
        "sampleTestCases": [
            {"input": "5\n1 5\n2 6\n4 7\n6 9\n8 10\n", "output": "3", "explanation": "Between time 4 and 5, the first three meetings overlap."},
            {"input": "4\n1 2\n2 3\n3 4\n4 5\n", "output": "1", "explanation": "Because an ending time is not occupied, adjacent meetings do not overlap."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Sort starts and ends separately and sweep them, processing an end before a start at the same time because intervals are end-exclusive.",
        "referenceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];starts=[];ends=[]\nfor i in range(n):starts.append(a[1+2*i]);ends.append(a[2+2*i])\nstarts.sort();ends.sort();i=j=cur=ans=0\nwhile i<n:\n if starts[i]<ends[j]:cur+=1;ans=max(ans,cur);i+=1\n else:cur-=1;j+=1\nprint(ans)",
        "bruteForceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];ev=[]\nfor i in range(n):\n s,e=a[1+2*i],a[2+2*i];ev.append((s,1));ev.append((e,-1))\nev.sort(key=lambda z:(z[0],z[1]));cur=ans=0\nfor _,v in ev:cur+=v;ans=max(ans,cur)\nprint(ans)",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,25));lines=[]\nfor _ in range(n):\n s=r.randint(0,100);e=r.randint(s+1,101);lines.append((s,e))\nprint(n);print('\\n'.join(f'{s} {e}' for s,e in lines))",
        "inputValidator": "import sys\ntry:\n a=list(map(int,sys.stdin.buffer.read().split()));n=a[0];assert 1<=n<=200000 and len(a)==1+2*n\n for i in range(n):\n  s,e=a[1+2*i],a[2+2*i];assert 0<=s<e<=10**9\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1\n0 1\n","2\n0 10\n10 20\n","5\n0 10\n0 10\n0 10\n0 10\n0 10\n","4\n1 2\n2 3\n3 4\n4 5\n","5\n1 5\n2 4\n3 6\n4 7\n5 8\n","4\n0 1000000000\n1 2\n3 4\n5 6\n"],
        "wrongSolutions": [
            {"name": "start_before_end", "description": "Treats a meeting starting exactly when another ends as overlapping.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];ev=[]\nfor i in range(n):ev += [(a[1+2*i],1),(a[2+2*i],-1)]\nev.sort(key=lambda z:(z[0],-z[1]));cur=ans=0\nfor _,v in ev:cur+=v;ans=max(ans,cur)\nprint(ans)"},
            {"name": "max_starts", "description": "Counts starts without removing meetings that have already ended.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];print(max(i+1 for i in range(n)))"},
            {"name": "too_slow_but_correct", "description": "Checks overlap count at every endpoint against every interval, resulting in quadratic time.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];x=[(a[1+2*i],a[2+2*i]) for i in range(n)];pts=sorted(set([v for p in x for v in p]));print(max(sum(s<=t<e for s,e in x) for t in pts))"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
    {
        "slug": "priority_ticket_dispatch",
        "title": "Priority Ticket Dispatch",
        "topic": "Stack & Queue",
        "difficulty": "Hard",
        "tags": ["priority-queue", "heap", "simulation"],
        "domains": ["backend", "devops"],
        "statement": "A support center receives tickets in chronological order. Each ticket has an arrival time and a priority, where a larger priority value is more urgent. The center has one agent. Whenever the agent is free, it chooses the available ticket with highest priority; if several available tickets have the same priority, it chooses the ticket with the smaller ID. Processing a ticket takes one second per unit of its duration. Simulate the dispatch order and print the IDs in the order they finish.",
        "inputFormat": "Line 1 contains n. Each of the next n lines contains three integers arrival, priority, and duration for ticket i, where i is its 1-based ID.",
        "outputFormat": "Print the n ticket IDs in the order they finish, separated by spaces.",
        "constraints": "1 <= n <= 200000. 0 <= arrival <= 10^9. 1 <= priority <= 10^9. 1 <= duration <= 10^9. Ticket arrival times are not necessarily distinct.",
        "sampleTestCases": [
            {"input": "5\n0 2 4\n1 5 2\n2 3 1\n6 5 2\n6 1 1\n", "output": "1 2 4 3 5", "explanation": "Ticket 1 starts at time 0 and finishes at 4. Tickets 2 and 3 are waiting, so ticket 2 goes next. At time 6, tickets 3, 4, and 5 are available; priority 5 ticket 4 is selected, then ticket 3, then ticket 5."},
            {"input": "4\n3 1 2\n3 4 1\n3 4 3\n10 2 1\n", "output": "2 3 1 4", "explanation": "At time 3, tickets 2 and 3 tie on priority, so the smaller ID, 2, is processed first. Ticket 3 follows, then ticket 1, and finally ticket 4 after it arrives."},
        ],
        "checker": "exact", "timeLimit": 2.0, "memoryLimit": 256,
        "coreIdea": "Sort tickets by arrival time and use a max-heap keyed by priority and negative ID while advancing time to the next arrival whenever the heap is empty.",
        "referenceSolution": "import sys,heapq\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];jobs=[]\nfor i in range(n):jobs.append((a[1+3*i],a[2+3*i],a[3+3*i],i+1))\njobs.sort();h=[];idx=0;t=0;out=[]\nwhile idx<n or h:\n if not h and t<jobs[idx][0]:t=jobs[idx][0]\n while idx<n and jobs[idx][0]<=t:\n  ar,p,d,j=jobs[idx];heapq.heappush(h,(-p,j,d));idx+=1\n pneg,j,d=heapq.heappop(h);t+=d;out.append(j)\nprint(*out)",
        "bruteForceSolution": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];jobs=[]\nfor i in range(n):jobs.append([a[1+3*i],a[2+3*i],a[3+3*i],i+1])\nt=0;done=[];remaining=set(range(n))\nwhile remaining:\n avail=[i for i in remaining if jobs[i][0]<=t]\n if not avail:t=min(jobs[i][0] for i in remaining);avail=[i for i in remaining if jobs[i][0]<=t]\n i=min(avail,key=lambda i:(-jobs[i][1],jobs[i][3]));t+=jobs[i][2];done.append(jobs[i][3]);remaining.remove(i)\nprint(*done)",
        "inputGenerator": "import sys,random\nr=random.Random(int(sys.argv[1]));m=sys.argv[2];n=200000 if m=='large' else (1 if m=='edge' else r.randint(1,18));lines=[]\nfor i in range(n):lines.append((r.randint(0,100) if m!='large' else r.randint(0,10**9),r.randint(1,20),r.randint(1,20)))\nprint(n);print('\\n'.join(f'{x} {y} {z}' for x,y,z in lines))",
        "inputValidator": "import sys\ntry:\n a=list(map(int,sys.stdin.buffer.read().split()));n=a[0];assert 1<=n<=200000 and len(a)==1+3*n\n for i in range(n):\n  ar,p,d=a[1+3*i:4+3*i];assert 0<=ar<=10**9 and 1<=p<=10**9 and 1<=d<=10**9\nexcept:sys.exit(1)\nsys.exit(0)",
        "edgeCaseInputs": ["1\n0 1 1\n","3\n0 1 5\n0 1 1\n0 1 2\n","4\n0 1 1\n0 2 1\n0 3 1\n0 4 1\n","5\n0 5 10\n1 1 1\n2 1 1\n3 1 1\n4 10 1\n","4\n100 1 1\n0 2 1\n0 2 1\n0 2 1\n","3\n0 1000000000 1000000000\n0 1 1\n1000000000 5 1\n"],
        "wrongSolutions": [
            {"name": "fifo_dispatch", "description": "Processes available tickets by arrival order instead of priority.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];j=[]\nfor i in range(n):j.append((a[1+3*i],i+1,a[3+3*i]))\nj.sort();print(' '.join(str(i) for _,i,_ in j))"},
            {"name": "priority_only", "description": "Breaks equal-priority ties by arrival order instead of the smaller ticket ID.", "code": "import sys,heapq\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];j=[]\nfor i in range(n):j.append((a[1+3*i],a[2+3*i],a[3+3*i],i+1))\nj.sort();h=[];idx=0;t=0;o=[]\nwhile idx<n or h:\n if not h:t=max(t,j[idx][0])\n while idx<n and j[idx][0]<=t:\n  ar,p,d,k=j[idx];heapq.heappush(h,(-p,ar,k,d));idx+=1\n _,_,k,d=heapq.heappop(h);t+=d;o.append(k)\nprint(*o)"},
            {"name": "too_slow_but_correct", "description": "Scans every remaining ticket to choose the next one, producing quadratic behavior.", "code": "import sys\na=list(map(int,sys.stdin.buffer.read().split()));n=a[0];j=[]\nfor i in range(n):j.append([a[1+3*i],a[2+3*i],a[3+3*i],i+1])\nt=0;rem=list(range(n));out=[]\nwhile rem:\n av=[i for i in rem if j[i][0]<=t]\n if not av:t=min(j[i][0] for i in rem);av=[i for i in rem if j[i][0]<=t]\n i=min(av,key=lambda i:(-j[i][1],j[i][3]));t+=j[i][2];out.append(j[i][3]);rem.remove(i)\nprint(*out)"},
        ],
        "hiddenTestPlan": {"small": 5, "edge": "all edgeCaseInputs", "large": 4, "weightSmall": 40, "weightLarge": 60},
        "source": "original", "status": "draft",
    },
]
