"""
Cheating Report Model
Defines the cheating_reports document structure and MongoDB document operations.
"""

from datetime import datetime
from bson import ObjectId


class CheatingReport:
    """
    Represents a cheating_reports MongoDB document.

    A cheating report is a derived risk assessment generated by analyzing
    historical proctoring logs for a candidate's interview session.
    """

    COLLECTION = "cheating_reports"

    @staticmethod
    def create_report(
        interview_id,
        user_id,
        risk_score: float,
        risk_level: str,
        total_events: int,
        suspicious_events: int,
        event_counts: dict,
        event_contributions: dict,
    ):
        """
        Build a new cheating_reports document dict ready for MongoDB insertion or upsert.

        Args:
            interview_id: str or ObjectId — the parent interview identifier.
            user_id: str or ObjectId — the candidate identifier.
            risk_score: float — normalized risk score (0 to 100).
            risk_level: str — derived risk category (LOW, MEDIUM, HIGH, CRITICAL).
            total_events: int — count of all proctoring logs.
            suspicious_events: int — count of proctoring logs with weight > 0.
            event_counts: dict — map of eventType -> actual count.
            event_contributions: dict — details showing count, effectiveCount, weight, contribution.

        Returns:
            dict ready to pass to MongoDB update/upsert operations.
        """
        now = datetime.utcnow()
        status_map = {"LOW": "LOW", "MEDIUM": "MODERATE", "HIGH": "HIGH", "CRITICAL": "CRITICAL"}
        status_val = status_map.get(risk_level.upper(), "LOW")

        violations_obj = {
            "faceMissing": event_counts.get("NO_FACE", 0),
            "multipleFaces": event_counts.get("MULTIPLE_FACES", 0),
            "tabSwitch": event_counts.get("TAB_SWITCH", 0),
            "windowMinimized": event_counts.get("FULLSCREEN_EXIT", 0),
            "backgroundVoice": event_counts.get("BACKGROUND_VOICE", 0),
        }

        return {
            "_id": ObjectId(),
            "interviewId": ObjectId(interview_id),
            "userId": ObjectId(user_id),
            "riskScore": float(risk_score),
            "riskLevel": risk_level,
            "status": status_val,
            "violations": violations_obj,
            "totalEvents": int(total_events),
            "suspiciousEvents": int(suspicious_events),
            "eventCounts": event_counts,
            "eventContributions": event_contributions,
            "createdAt": now,
            "updatedAt": now,
        }

    @staticmethod
    def response(report):
        """
        Serialize a cheating_reports MongoDB document for an API response.

        Args:
            report: dict — raw MongoDB document from the cheating_reports collection.

        Returns:
            dict safe for JSON serialisation.
        """
        created_at_val = report.get("createdAt")
        updated_at_val = report.get("updatedAt")

        return {
            "id": str(report["_id"]),
            "interviewId": str(report["interviewId"]),
            "userId": str(report["userId"]),
            "riskScore": report["riskScore"],
            "riskLevel": report["riskLevel"],
            "totalEvents": report["totalEvents"],
            "suspiciousEvents": report["suspiciousEvents"],
            "eventCounts": report["eventCounts"],
            "eventContributions": report["eventContributions"],
            "createdAt": created_at_val.isoformat() if isinstance(created_at_val, datetime) else created_at_val,
            "updatedAt": updated_at_val.isoformat() if isinstance(updated_at_val, datetime) else updated_at_val,
        }
